### ISSUE TITLE
Infinite loop in text.Wrap() if input is lacking spaces

### ISSUE THREAD

**Issue by 011010101101** [kr/text#1]
When calling text.Wrap(), if the input string:
1. has no spaces, and
2. is longer than the wrap size, 
then the function will loop forever and consume all available memory.

Sample program (be careful running this, it will consume all available memory):

```
package main

import (
    "github.com/kr/text"
)

func main() {
    text.Wrap("aaaaa", 4)
}
```

**Comment by aaudis** [comment]
I also need this issue to be fixed

Waiting, Thanks
