### ISSUE TITLE
Go version is very old

### ISSUE THREAD

**Issue by vault-thirteen** [kr/text#19]
The current library uses Go language verion 1.12.

> go 1.12

This version is very old. 
Version 1.12 was released in February 2019 according to the Go's website, https://go.dev/project.
Today is February 2023. Four (4) years have passed !

Thank you.

**Comment by kr** [comment]
Hi, thanks for filing the issue. Don't worry, the Go version listed in go.mod isn't a requirement. It's common to build Go modules with a more recent version of the compiler than what's listed in go.mod. You can use any version of Go you want, and Go provides [strong compatibility](https://go.dev/doc/go1compat) from one version to the next.
