### ISSUE TITLE
Master branch deleted

### ISSUE THREAD

**Issue by thdxr** [kr/text#8]
Hey you seemed to have deleted the master branch of this project and now go get commands are failing all over the system.  Could you please revert? Thanks

**Comment by r3m0chop** [comment]
ditto, and we were trying to track that down as well - thanks for creating this issue.
looks like it has been reported in different ways for the following issues as well: #6 & #7

**Comment by TomDeVito** [comment]
+1

**Comment by ronniekritou** [comment]
> +1

**Comment by yedidmh** [comment]
+1

**Comment by Incisive** [comment]
+1  Had to manually checkout "main" branch to get this working for now.

**Comment by bmoyles0117** [comment]
+1

**Comment by kr** [comment]
Dup of #6.
